apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: nginx
spec:
  type: {{.Values.service.type}}
  selector:
    app: nginx
  ports:
    - protocol: TCP
      # port where service is listening
      port: {{.Values.service.port}}
      # port where container is listening
      targetPort: {{.Values.containerPorts.http}}
