apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
type: Opaque
data:
  # @see https://argo-cd.readthedocs.io/en/release-2.2/faq/
  # htpasswd -bnBC 10 "" admin | tr -d ':\n' | base64
  admin.password: "JDJ5JDEwJEMxQ1JoU0pMdEg1MmR6WTY3bXRuUHVuamx5TjUvaEkwMHhSa0VsZ0FRWEJ3eFNjMXdGVTFT"
