apiVersion: v1
kind: Service
metadata:
  labels:
    app: webserver-service
  name: webserver-service
  namespace: webapp
spec:
  ports:
    - name: http      # わかりやすい名前に変更
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: webserver  # Pod のラベルに合わせて変更
  type: ClusterIP
