apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  destination:
    name: minikube
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
