apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - ../../base
  - ingress.yaml
patches:
  - path: guestbook/project.yaml
  - path: guestbook/application.yaml
